Propagate events to hidden widgets in `Either`
linebender/druid pull request #1351
Opened 2020-10-27 19:50 UTC by andrewhickman

Fixes #1350

2020-10-29 15:03 UTC, jneem approved these changes
Makes sense to me.

2020-10-29 21:01 UTC, andrewhickman commented
This currently has an issue when using a `Spinner` (or other animated widget). `Either` doesn't lay out its hidden child, so there is a warning when it gets `AnimFrame` events. I'm not sure whether it should lay out both children (as `Tabs` does) or not send `AnimFrame` events to the child

2020-10-29 21:43 UTC, andrewhickman commented
I've changed the warning to only be emitted for events that have `should_propagate_to_hidden() == false`. @cmyr does that sound reasonable? It means `Event::Command` and `Event::AnimFrame` will no longer generate the warning.

2020-10-30 10:18 UTC, Finnerale requested changes
This should have a changlog entry (probably multiple)

2020-10-30 18:32 UTC, Finnerale approved these changes
Thanks!

2020-10-30 21:37 UTC, andrewhickman commented
CI had a spurious error but that seems to have resolved itself now

2020-10-31 15:06 UTC, Finnerale commented
@andrewhickman this looks good to me, should we merge it?

2020-10-31 15:11 UTC, andrewhickman commented
Yep, its ready to merge 👍

2020-10-31 15:50 UTC, merged