druid-shell: Added Delete key handling
linebender/druid pull request #1746
Opened 2021-04-28 14:25 UTC by bjorn

As I was trying the examples on Linux I noticed that whereas Backspace was handled, the Delete key was not. I hope I found the right way to add this functionality (it works at least).

2021-05-01 20:39 UTC, jneem requested changes
Thanks, this makes sense to me, at least. Just one typo in the changelog...

2021-05-01 20:39 UTC, jneem commented on CHANGELOG.md
> +[#1726]: https://github.com/linebender/druid/pull/1726
1746, no?

2021-05-02 19:33 UTC, jneem approved these changes

2021-05-03 16:35 UTC, cmyr commented
Yep, this is definitely right; there's a bunch of stuff missing from this "simulate_input" method, and fixes are welcome!

2021-05-03 16:36 UTC, merged

2021-05-04 08:37 UTC, bjorn commented
@cmyr I had just run into the missing Delete handling myself. What other stuff is known to be missing?

2021-05-04 13:52 UTC, cmyr commented
I suspect most modifier combos like ctrl+arrow are missing. Also it might be nice, on linux, to support all the basic readline combos, like ctrl+e, ctrl+a, etcetera?