Update README.md example to match version 0.7.0
linebender/druid pull request #1750
Opened 2021-04-30 16:19 UTC by hammsvietro

As discussed in #1748, although not implied, the README.md example isn't building if using the version mentioned below, 0.7.0. maybe this could avoid troubleshooting for a newcomer.

2021-04-30 17:24 UTC, SecondFlight commented
The issue to me is not that the example implies 0.7.0; it's that the version in the example is ambiguous. Both `0.7.0` and `master` are mentioned in the readme, and it's not clear which one the example is targeting. My gut feeling is that, unless something is clarified, changing the example to target `0.7.0` will help some people but confuse others.

I think there is a case to be made for having the example on GitHub target the version on GitHub; the [docs](https://docs.rs/druid/0.7.0/druid/) provide an example targeting 0.7.0, so that's covered. The potential issue with the readme is that it's not clear that it targets master.

Any other thoughts? I'd like to avoid completely driving this, so I'll wait for someone else to chime in with thoughts/suggestions.

2021-05-01 21:25 UTC, jneem commented
I think it makes sense to have the readme follow master, with a link to the 0.7.0 docs for those who want a slower-moving target.

2021-05-03 14:50 UTC, cmyr commented
Agreed, it's going to be too much of a headache to not keep the readme in line with master.

2021-05-04 15:08 UTC, SecondFlight commented
@hammsvietro I don't think this PR will merge as-is, but I think a possible solution here would be to
1. Revert the example change
2. Make a note saying the example uses master
3. Link to the docs for a 0.7.0 example

I think this is a good change and I'll do it soon if there's no new activity here, but I want to give you the chance to if you'd like, or to suggest something else.

2021-05-04 16:05 UTC, hammsvietro commented
that makes sense, I did as you suggested

2021-05-12 17:25 UTC, SecondFlight requested changes
Sorry for the late review. I haven't had time to dedicate to this until today.

These are just some minor nitpicks. I've replaced the crates.io link with docs.rs - this is more of a preference thing. docs.rs has a lot more documentation than just examples, so I like the idea of pointing there.

I'll apply these changes and merge tomorrow.

2021-05-12 17:25 UTC, SecondFlight commented on README.md
> +
```suggestion
This example works with master. Here's an example for 0.7.0: https://docs.rs/druid/latest/druid/#examples.
```

2021-05-12 18:17 UTC, SecondFlight approved these changes

2021-05-12 19:44 UTC, merged

2021-05-12 19:46 UTC, SecondFlight commented
Thanks!

2021-05-12 19:50 UTC, cmyr commented
Thaanks @hammsvietro and @SecondFlight, I think this is a good compromise!

2021-05-12 20:02 UTC, hammsvietro commented
really like the project, glad that I could help in some way 😃