Update CI config file to optimize CI times.
linebender/druid pull request #1934
Opened 2021-08-24 14:50 UTC by PoignardAzur

Replace nightly builds with single beta build. Make the build not block 
CI on error.
Only run wasm build on a single OS.

This should overall make the project use less CI cache; Github actions 
cache is capped at 5GB per project, whereas the previous CI used about 
6GB. This meant cache entries were systematically evicted before they 
could be used.

2021-08-24 17:44 UTC, PoignardAzur commented
CI times now hover around 5 minutes. This should be ready to merge.

2021-08-25 10:38 UTC, Maan2003 requested changes
accidentally removed clippy for wasm and gtk

2021-08-25 10:38 UTC, Maan2003 commented on .github/workflows/ci.yml
> +          args: --manifest-path=druid/Cargo.toml --doc --no-default-features --features=svg,image,im,x11
do not enable x11 on macos :)
```suggestion
          args: --manifest-path=druid/Cargo.toml --doc --no-default-features --features=svg,image,im
```

2021-08-25 10:38 UTC, Maan2003 commented on .github/workflows/ci.yml
> -          args: --manifest-path=druid-shell/Cargo.toml --all-targets -- -D warnings
Are we running clippy for druid_shell/gtk anywhere?

2021-08-25 10:38 UTC, Maan2003 commented on .github/workflows/ci.yml
> -
again are running clippy on druid-shell/web anywhere?

2021-08-25 10:38 UTC, Maan2003 commented on .github/workflows/ci.yml
> +          args: --manifest-path=druid/Cargo.toml --doc --no-default-features --features=svg,image,im,x11
```suggestion
          args: --manifest-path=druid/Cargo.toml --doc --no-default-features --features=svg,image,im
```

2021-08-25 14:13 UTC, PoignardAzur commented
Oops, yeah, I got a little too enthusiastic with the guillotine there.

Amended commit keeps the clippy run for wasm and gtk versions of druid-shell. Should still run in about 5min, since druid-shell is fairly small.

2021-08-25 14:35 UTC, Maan2003 approved these changes
Thanks!  This is awesome :tada:

2021-08-25 14:37 UTC, merged

2021-08-25 14:37 UTC, PoignardAzur commented
This makes my own life easier. I just hate waiting for CI ^^