add freebsd target
linebender/druid pull request #2249
Opened 2022-08-27 13:48 UTC by nunotexbsd

add freebsd target for lapce freebsd port
https://github.com/lapce/lapce/pull/985

2022-09-02 11:47 UTC, nunotexbsd commented
Hi,

Can't understand why checks are failing by adding freebsd target. It builds fine in freebsd.
Any hints on how to fix this?

Thanks

2022-09-12 16:01 UTC, jneem commented
In the logs for `cargo clippy+test (ubuntu-latest)`, it's failing on some missing imports. Maybe they're `cfg`ed out somehow?

2022-09-12 16:19 UTC, nunotexbsd commented
I did this changes manually so maybe something is missing.
Is there a possibility of replacing openbsd with freebsd targets for testing purposes?

freebsd target was merged in https://github.com/lapce/lapce/pull/985 and lapce is running fine with freebsd patched druid at https://www.freshports.org/editors/lapce/

2022-09-13 22:13 UTC, panekj requested changes

2022-09-13 22:13 UTC, panekj commented on druid-shell/src/backend/shared/mod.rs
> +    if #[cfg(all(target_os = "freebsd", target_os = "linux", any(feature = "x11", feature = "wayland")))] {
```suggestion
    if #[cfg(all(any(target_os = "freebsd", target_os = "linux"), any(feature = "x11", feature = "wayland")))] {
```

2022-09-14 00:14 UTC, nunotexbsd commented on druid-shell/src/backend/shared/mod.rs
> +    if #[cfg(all(target_os = "freebsd", target_os = "linux", any(feature = "x11", feature = "wayland")))] {
Thanks! let's wait for results :)

2022-09-14 11:37 UTC, nunotexbsd commented
> In the logs for `cargo clippy+test (ubuntu-latest)`, it's failing on some missing imports. Maybe they're `cfg`ed out somehow?

@jneem I did understanded @panekj sugestion changes and it fixed almost all tests.
I've checked cargo fmt build log but I don't see what can be done here because I don't see a more detailed error.

Any hint?

Thanks

2022-09-14 11:37 UTC, panekj commented
just need `cargo fmt` on the code and it should be fine

2022-09-14 11:55 UTC, nunotexbsd commented
nice!
> just need cargo fmt on the code and it should be fine
So I must wait that someone include that code?

Thanks!

2022-09-14 13:39 UTC, panekj commented
On your branch run `cargo fmt` and commit the code

2022-09-14 18:24 UTC, nunotexbsd commented
Done!

Thanks @panekj!

2022-09-18 20:30 UTC, jneem approved these changes

2022-09-18 20:30 UTC, merged