Various documentation-related fixes
linebender/druid pull request #2301
Opened 2022-12-07 15:19 UTC by PoignardAzur

Move and expand doc on hot and active status.
Document crate options.
Add discontinuation notice.
Remove crochet stuff.
Fix typos.
Fix broken link.
Fix outdated doc links.
Fix examples/readme.md.

2023-01-04 14:17 UTC, xStrom requested changes
Please rebase this on `master` and resolve the conflicting `druid/src/contexts.rs` file.

I reviewed the other files and generally it looks like a good set of updates.

Thanks for taking the time!

2023-01-04 14:17 UTC, xStrom commented on docs/src/03_data.md
> +It is important that your data be cheap to clone and cheap to compare; we encourage the use of reference counted pointers to allow cheap cloning of more expensive types. `Arc` and `Rc` have blanket `
```suggestion
It is important that your data is cheap to clone and cheap to compare; we encourage the use of reference counted pointers to allow cheap cloning of more expensive types. `Arc` and `Rc` have blanket `Data` impls that do pointer comparison, so if you have a type that does not implement `Data`, you can always just wrap it in one of those smart pointers.
```

Alternatively *are* if data is plural, but I think that would confuse more people so I went with singular data.

2023-01-04 14:17 UTC, xStrom commented on docs/src/03_data.md
> +the [`im crate`], and adds a `Data` impl for the collections there. The [`im`
```suggestion
the [`im` crate], and adds a `Data` impl for the collections there. The [`im`
```
The link is defined this way.

2023-01-04 14:17 UTC, xStrom commented on docs/src/03_data.md
> +In some cases, however, you want compose widgets that operate on different subsets of the data. Maybe you want to add two widgets to the above Flex, one that uses the field `foo` and another that use
```suggestion
In some cases, however, you want to compose widgets that operate on different subsets of the data. Maybe you want to add two widgets to the above `Flex`, one that uses the field `foo` and another that uses the field `bar`, and they might respectively implement `Widget<Foo>` and `Widget<Bar>`.
```

2023-01-06 11:36 UTC, PoignardAzur commented
Sorry, haven't had too much bandwidth lately. I'll try to fix the PR this weekend.

2023-01-06 12:01 UTC, xStrom commented
No worries, I'm aware as you know 🙂 Whenever you find it reasonable.

2023-01-10 17:50 UTC, PoignardAzur commented
Alright, I've rebased and applied some of your suggestions.

2023-01-10 20:18 UTC, xStrom approved these changes
Excellent, I think it's good to merge! 🙂

2023-01-12 13:24 UTC, merged